package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/ACTIVE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/jenkins/workspace/8-2-build-linux-amd64/jdk8u291/1294/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Wednesday, April 7, 2021 7:14:19 PM GMT
*/

public interface ACTIVE
{

  /** Object adapter state that indicates normal request processing.
     */
  public static final short value = (short)(1);
}
